name: Semgrep Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '20 11 * * *'

jobs:
  semgrep:
    name: semgrep-ci
    runs-on: ubuntu-latest

    permissions:
      contents: read

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run aggressive Semgrep scan
        run: |
          semgrep \
          --config=p/nodejs \
          --config=p/javascript \
          --config=p/owasp-top-ten \
          --config=p/secrets \
          --exclude semgrep-report.json \
          --json > semgrep-report.json

      - name: Print findings count
        run: |
          cat semgrep-report.json | jq '.results | length'

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Send findings to n8n webhook
        run: |
          curl -X POST "${{ secrets.N8N_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          --data @semgrep-report.json